export const authConstants={
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGIN_SUCESS:'LOGIN_SUCESS',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCESS:'LOGOUT_SUCESS',
    LOGOUT_FAILURE:'LOGOUT_FAILURE'
}